#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: Dispatch-station
    username: user
    password: $6$rounds=4096$salt$ZrJvsbPXcziLjTvYIUnMTp/Oz.Vxyc4YfKh0zbHSx7IkGJx0uYpuizEknMqItECgOsIsEuYmNoS7G/Mr2cCMs1
    realname: User
  packages:
    - cockpit
    - unattended-upgrades
  late-commands:
    - curtin in-target --target=/target snap install remmina
    - curtin in-target --target=/target systemctl enable cockpit.socket
    - curtin in-target --target=/target systemctl enable unattended-upgrades
    - echo -e '[daemon]\nAutomaticLoginEnable=true\nAutomaticLogin=user' | tee -a /target/etc/gdm3/custom.conf
